--  Generate SQL 
--  Version:                   	V7R5M0 220415 
--  Generated on:              	25-12-25 22:51:40 
--  Relational Database:       	PUB400 
--  Standards Option:          	Db2 for i 
CREATE TABLE MMOEGLING1.IMDB_GENRES FOR SYSTEM NAME IMDBGENR ( 
	GENRE_ID FOR COLUMN GENREID    INTEGER GENERATED ALWAYS AS IDENTITY ( 
	START WITH 1 INCREMENT BY 1 
	NO MINVALUE NO MAXVALUE 
	NO CYCLE NO ORDER 
	CACHE 20 ) 
	, 
	GENRE CHAR(25) CCSID 273 NOT NULL , 
	CONSTRAINT MMOEGLING1.Q_MMOEGLING1_IMDBGENR_GENREID_00001 PRIMARY KEY( GENRE_ID ) )   
	  
	RCDFMT IMDBGENR   ; 
  
LABEL ON TABLE MMOEGLING1.IMDB_GENRES 
	IS 'IMDB Genres' ; 
  
LABEL ON COLUMN MMOEGLING1.IMDB_GENRES 
( GENRE_ID TEXT IS 'Genres ID' , 
	GENRE TEXT IS 'Genre' ) ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON MMOEGLING1.IMDB_GENRES TO MMOEGLING WITH GRANT OPTION ; 
  
