--  Generate SQL 
--  Version:                   	V7R5M0 220415 
--  Generated on:              	25-12-25 22:25:31 
--  Relational Database:       	PUB400 
--  Standards Option:          	Db2 for i 
CREATE TABLE MMOEGLING1.IMDB_GENRES_IN FOR SYSTEM NAME IMDB_00001 ( 
	TEMP_GENRES FOR COLUMN GENRES     CHAR(50) CCSID 273 DEFAULT NULL )   
	  
	RCDFMT IMDB_00001 ; 
  
LABEL ON TABLE MMOEGLING1.IMDB_GENRES_IN 
	IS 'Temp Table Genres Inbound' ; 
  
LABEL ON COLUMN MMOEGLING1.IMDB_GENRES_IN 
( TEMP_GENRES TEXT IS 'Temp_genres' ) ; 
  
GRANT ALTER , DELETE , INDEX , INSERT , REFERENCES , SELECT , UPDATE   
ON MMOEGLING1.IMDB_GENRES_IN TO MMOEGLING WITH GRANT OPTION ; 
  
